import example_03_test_module

print(example_03_test_module.convert_celsius_to_fahrenheit(20))
print(example_03_test_module.convert_celsius_to_fahrenheit(25))
print(example_03_test_module.convert_celsius_to_fahrenheit(30))